name: React build

on:
  push:
    branches:
      - temp/test-workflow  # temp/test-workflow 브랜치에 푸시될 때 실행
  workflow_dispatch:   # GitHub UI에서 'Run workflow' 버튼을 눌러 수동으로 실행할 수 있도록 설정

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # 레포지토리 체크아웃
        uses: actions/checkout@v2 #main을 직접 참조하는게 아니라 최신 버전을 참조

      - name: Cache node modules # node modules 캐싱
        uses: actions/cache@v2
        with:
          path: node_modules # 프로젝트의 node_modules가 있는 경로로 설정
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies # 의존 파일 설치
        run: npm install # npm install을 실행할 경로로 설정

      - name: Build # React Build
        run: npm run build # npm run build를 실행할 경로로 설정

      - name: Deploy # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 rm s3://damdda-frontend-bucket/ --recursive
          aws s3 cp build/ s3://damdda-frontend-bucket/ --recursive